name: R Lint with Reviewdog

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    name: Run lintr with reviewdog
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write  # Required for posting PR comments

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install lintr
        run: Rscript -e 'install.packages("lintr")'

      - name: Run lintr and report via reviewdog
        uses: reviewdog/action-suggester@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tool_name: lintr
          fail_on_error: true
          filter_mode: diff_context
          reporter: github-pr-review
          run: Rscript -e 'lintr::lint_dir(linters = lintr::default_linters())'
